// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: Qot_SetPriceReminder.proto

package qotsetpricereminder

import (
	encoding_binary "encoding/binary"
	fmt "fmt"
	_ "github.com/futuopen/ftapi4go/pb/common"
	qotcommon "github.com/futuopen/ftapi4go/pb/qotcommon"
	github_com_gogo_protobuf_proto "github.com/gogo/protobuf/proto"
	proto "github.com/gogo/protobuf/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type SetPriceReminderOp int32

const (
	SetPriceReminderOp_SetPriceReminderOp_Unknown SetPriceReminderOp = 0
	SetPriceReminderOp_SetPriceReminderOp_Add     SetPriceReminderOp = 1
	SetPriceReminderOp_SetPriceReminderOp_Del     SetPriceReminderOp = 2
	SetPriceReminderOp_SetPriceReminderOp_Enable  SetPriceReminderOp = 3
	SetPriceReminderOp_SetPriceReminderOp_Disable SetPriceReminderOp = 4
	SetPriceReminderOp_SetPriceReminderOp_Modify  SetPriceReminderOp = 5
)

var SetPriceReminderOp_name = map[int32]string{
	0: "SetPriceReminderOp_Unknown",
	1: "SetPriceReminderOp_Add",
	2: "SetPriceReminderOp_Del",
	3: "SetPriceReminderOp_Enable",
	4: "SetPriceReminderOp_Disable",
	5: "SetPriceReminderOp_Modify",
}

var SetPriceReminderOp_value = map[string]int32{
	"SetPriceReminderOp_Unknown": 0,
	"SetPriceReminderOp_Add":     1,
	"SetPriceReminderOp_Del":     2,
	"SetPriceReminderOp_Enable":  3,
	"SetPriceReminderOp_Disable": 4,
	"SetPriceReminderOp_Modify":  5,
}

func (x SetPriceReminderOp) Enum() *SetPriceReminderOp {
	p := new(SetPriceReminderOp)
	*p = x
	return p
}

func (x SetPriceReminderOp) String() string {
	return proto.EnumName(SetPriceReminderOp_name, int32(x))
}

func (x *SetPriceReminderOp) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(SetPriceReminderOp_value, data, "SetPriceReminderOp")
	if err != nil {
		return err
	}
	*x = SetPriceReminderOp(value)
	return nil
}

func (SetPriceReminderOp) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_2d9154bf16c2c7ce, []int{0}
}

type C2S struct {
	Security *qotcommon.Security `protobuf:"bytes,1,req,name=security" json:"security,omitempty"`
	Op       int32               `protobuf:"varint,2,req,name=op" json:"op"`
	Key      int64               `protobuf:"varint,3,opt,name=key" json:"key"`
	Type     int32               `protobuf:"varint,4,opt,name=type" json:"type"`
	Freq     int32               `protobuf:"varint,7,opt,name=freq" json:"freq"`
	Value    float64             `protobuf:"fixed64,5,opt,name=value" json:"value"`
	Note     string              `protobuf:"bytes,6,opt,name=note" json:"note"`
}

func (m *C2S) Reset()         { *m = C2S{} }
func (m *C2S) String() string { return proto.CompactTextString(m) }
func (*C2S) ProtoMessage()    {}
func (*C2S) Descriptor() ([]byte, []int) {
	return fileDescriptor_2d9154bf16c2c7ce, []int{0}
}
func (m *C2S) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *C2S) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_C2S.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *C2S) XXX_Merge(src proto.Message) {
	xxx_messageInfo_C2S.Merge(m, src)
}
func (m *C2S) XXX_Size() int {
	return m.Size()
}
func (m *C2S) XXX_DiscardUnknown() {
	xxx_messageInfo_C2S.DiscardUnknown(m)
}

var xxx_messageInfo_C2S proto.InternalMessageInfo

func (m *C2S) GetSecurity() *qotcommon.Security {
	if m != nil {
		return m.Security
	}
	return nil
}

func (m *C2S) GetOp() int32 {
	if m != nil {
		return m.Op
	}
	return 0
}

func (m *C2S) GetKey() int64 {
	if m != nil {
		return m.Key
	}
	return 0
}

func (m *C2S) GetType() int32 {
	if m != nil {
		return m.Type
	}
	return 0
}

func (m *C2S) GetFreq() int32 {
	if m != nil {
		return m.Freq
	}
	return 0
}

func (m *C2S) GetValue() float64 {
	if m != nil {
		return m.Value
	}
	return 0
}

func (m *C2S) GetNote() string {
	if m != nil {
		return m.Note
	}
	return ""
}

type S2C struct {
	Key int64 `protobuf:"varint,1,req,name=key" json:"key"`
}

func (m *S2C) Reset()         { *m = S2C{} }
func (m *S2C) String() string { return proto.CompactTextString(m) }
func (*S2C) ProtoMessage()    {}
func (*S2C) Descriptor() ([]byte, []int) {
	return fileDescriptor_2d9154bf16c2c7ce, []int{1}
}
func (m *S2C) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *S2C) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_S2C.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *S2C) XXX_Merge(src proto.Message) {
	xxx_messageInfo_S2C.Merge(m, src)
}
func (m *S2C) XXX_Size() int {
	return m.Size()
}
func (m *S2C) XXX_DiscardUnknown() {
	xxx_messageInfo_S2C.DiscardUnknown(m)
}

var xxx_messageInfo_S2C proto.InternalMessageInfo

func (m *S2C) GetKey() int64 {
	if m != nil {
		return m.Key
	}
	return 0
}

type Request struct {
	C2S *C2S `protobuf:"bytes,1,req,name=c2s" json:"c2s,omitempty"`
}

func (m *Request) Reset()         { *m = Request{} }
func (m *Request) String() string { return proto.CompactTextString(m) }
func (*Request) ProtoMessage()    {}
func (*Request) Descriptor() ([]byte, []int) {
	return fileDescriptor_2d9154bf16c2c7ce, []int{2}
}
func (m *Request) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Request) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Request.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Request) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Request.Merge(m, src)
}
func (m *Request) XXX_Size() int {
	return m.Size()
}
func (m *Request) XXX_DiscardUnknown() {
	xxx_messageInfo_Request.DiscardUnknown(m)
}

var xxx_messageInfo_Request proto.InternalMessageInfo

func (m *Request) GetC2S() *C2S {
	if m != nil {
		return m.C2S
	}
	return nil
}

type Response struct {
	RetType *int32 `protobuf:"varint,1,req,name=retType,def=-400" json:"retType,omitempty"`
	RetMsg  string `protobuf:"bytes,2,opt,name=retMsg" json:"retMsg"`
	ErrCode int32  `protobuf:"varint,3,opt,name=errCode" json:"errCode"`
	S2C     *S2C   `protobuf:"bytes,4,opt,name=s2c" json:"s2c,omitempty"`
}

func (m *Response) Reset()         { *m = Response{} }
func (m *Response) String() string { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()    {}
func (*Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_2d9154bf16c2c7ce, []int{3}
}
func (m *Response) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Response.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Response.Merge(m, src)
}
func (m *Response) XXX_Size() int {
	return m.Size()
}
func (m *Response) XXX_DiscardUnknown() {
	xxx_messageInfo_Response.DiscardUnknown(m)
}

var xxx_messageInfo_Response proto.InternalMessageInfo

const Default_Response_RetType int32 = -400

func (m *Response) GetRetType() int32 {
	if m != nil && m.RetType != nil {
		return *m.RetType
	}
	return Default_Response_RetType
}

func (m *Response) GetRetMsg() string {
	if m != nil {
		return m.RetMsg
	}
	return ""
}

func (m *Response) GetErrCode() int32 {
	if m != nil {
		return m.ErrCode
	}
	return 0
}

func (m *Response) GetS2C() *S2C {
	if m != nil {
		return m.S2C
	}
	return nil
}

func init() {
	proto.RegisterEnum("Qot_SetPriceReminder.SetPriceReminderOp", SetPriceReminderOp_name, SetPriceReminderOp_value)
	proto.RegisterType((*C2S)(nil), "Qot_SetPriceReminder.C2S")
	proto.RegisterType((*S2C)(nil), "Qot_SetPriceReminder.S2C")
	proto.RegisterType((*Request)(nil), "Qot_SetPriceReminder.Request")
	proto.RegisterType((*Response)(nil), "Qot_SetPriceReminder.Response")
}

func init() { proto.RegisterFile("Qot_SetPriceReminder.proto", fileDescriptor_2d9154bf16c2c7ce) }

var fileDescriptor_2d9154bf16c2c7ce = []byte{
	// 465 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x90, 0xcf, 0x6e, 0xd3, 0x40,
	0x10, 0xc6, 0xbd, 0xfe, 0xd3, 0x94, 0x85, 0x83, 0xb5, 0x44, 0x95, 0x6b, 0x51, 0x63, 0xe5, 0x64,
	0x81, 0x70, 0x22, 0x53, 0x71, 0xe0, 0x46, 0x5d, 0x8e, 0x15, 0x60, 0xc3, 0x85, 0x4b, 0x15, 0xdb,
	0x93, 0x60, 0x35, 0xf6, 0x6e, 0x76, 0xd7, 0xa0, 0xbc, 0x05, 0x17, 0xde, 0xa9, 0xe2, 0x42, 0x8f,
	0x9c, 0x10, 0x4a, 0x5e, 0x04, 0x6d, 0x6a, 0x57, 0x16, 0x4d, 0xae, 0xbf, 0xdf, 0x37, 0x9a, 0x6f,
	0x06, 0xbb, 0x1f, 0xa8, 0xbc, 0x4c, 0x41, 0xbe, 0xe7, 0x65, 0x0e, 0x09, 0x54, 0x65, 0x5d, 0x00,
	0x0f, 0x19, 0xa7, 0x92, 0x92, 0xe1, 0x2e, 0xe7, 0x3e, 0x8a, 0x69, 0x55, 0xd1, 0xfa, 0x36, 0xe3,
	0xda, 0x2a, 0xd3, 0x27, 0xa3, 0x5f, 0x08, 0x1b, 0x71, 0x94, 0x92, 0x09, 0x3e, 0x14, 0x90, 0x37,
	0xbc, 0x94, 0x2b, 0x07, 0xf9, 0x7a, 0xf0, 0x30, 0x1a, 0x86, 0xbd, 0x70, 0xda, 0xba, 0xe4, 0x2e,
	0x45, 0x86, 0x58, 0xa7, 0xcc, 0xd1, 0x7d, 0x3d, 0xb0, 0xce, 0xcc, 0xeb, 0x3f, 0x4f, 0xb5, 0x44,
	0xa7, 0x8c, 0x1c, 0x61, 0xe3, 0x0a, 0x56, 0x8e, 0xe1, 0xa3, 0xc0, 0x68, 0xb1, 0x02, 0xc4, 0xc1,
	0xa6, 0x5c, 0x31, 0x70, 0x4c, 0x1f, 0xdd, 0xe5, 0xb7, 0x44, 0x99, 0x19, 0x87, 0xa5, 0x33, 0xe8,
	0x1b, 0x45, 0x88, 0x8b, 0xad, 0xaf, 0xd3, 0x45, 0x03, 0x8e, 0xe5, 0xa3, 0x00, 0xb5, 0xea, 0x16,
	0xa9, 0xa9, 0x9a, 0x4a, 0x70, 0x0e, 0x7c, 0x14, 0x3c, 0xe8, 0xa6, 0x14, 0x19, 0x9d, 0x60, 0x23,
	0x8d, 0xe2, 0xae, 0x88, 0xba, 0xa5, 0x5f, 0x64, 0xf4, 0x0a, 0x0f, 0x12, 0x58, 0x36, 0x20, 0x24,
	0x79, 0x8e, 0x8d, 0x3c, 0x12, 0xed, 0xb9, 0xc7, 0xe1, 0xce, 0xdf, 0xc6, 0x51, 0x9a, 0xa8, 0xd4,
	0xe8, 0x07, 0xc2, 0x87, 0x09, 0x08, 0x46, 0x6b, 0x01, 0xc4, 0xc3, 0x03, 0x0e, 0xf2, 0xa3, 0x3a,
	0x48, 0x4d, 0x5b, 0xaf, 0xcd, 0x17, 0xa7, 0x93, 0x49, 0xd2, 0x41, 0xf2, 0x04, 0x1f, 0x70, 0x90,
	0x17, 0x62, 0xee, 0xe8, 0xbd, 0x7e, 0x2d, 0x53, 0xd3, 0xc0, 0x79, 0x4c, 0x0b, 0xd8, 0xfe, 0xa9,
	0x3b, 0xba, 0x83, 0xaa, 0x97, 0x88, 0xf2, 0xed, 0xab, 0xf6, 0xf6, 0x4a, 0xa3, 0x38, 0x51, 0xa9,
	0x67, 0x3f, 0x11, 0x26, 0xff, 0xdb, 0x77, 0x8c, 0x78, 0xd8, 0xbd, 0x4f, 0x2f, 0x3f, 0xd5, 0x57,
	0x35, 0xfd, 0x56, 0xdb, 0x1a, 0x71, 0xf1, 0xd1, 0x0e, 0xff, 0xa6, 0x28, 0x6c, 0xb4, 0xc7, 0x9d,
	0xc3, 0xc2, 0xd6, 0xc9, 0x09, 0x3e, 0xde, 0xe1, 0xde, 0xd6, 0xd3, 0x6c, 0x01, 0xb6, 0xb1, 0x67,
	0xed, 0x79, 0x29, 0xb6, 0xde, 0xdc, 0x33, 0x7e, 0x41, 0x8b, 0x72, 0xb6, 0xb2, 0xad, 0xb3, 0xec,
	0x7a, 0xed, 0xa1, 0x9b, 0xb5, 0x87, 0xfe, 0xae, 0x3d, 0xf4, 0x7d, 0xe3, 0x69, 0x37, 0x1b, 0x4f,
	0xfb, 0xbd, 0xf1, 0x34, 0xfc, 0x38, 0xa7, 0x55, 0x38, 0x6b, 0x64, 0x13, 0x52, 0x06, 0xf5, 0x94,
	0x95, 0x21, 0xcb, 0x3e, 0xbf, 0x9c, 0x97, 0xf2, 0x4b, 0x93, 0x85, 0x39, 0xad, 0xc6, 0xca, 0x29,
	0x35, 0x9e, 0xc9, 0x29, 0x2b, 0x4f, 0xe7, 0x74, 0xcc, 0xb2, 0xf1, 0x92, 0x4a, 0x01, 0x92, 0xa9,
	0x75, 0xbc, 0x5d, 0xf7, 0x2f, 0x00, 0x00, 0xff, 0xff, 0x1f, 0xc9, 0x63, 0x08, 0x44, 0x03, 0x00,
	0x00,
}

func (m *C2S) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *C2S) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *C2S) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	i = encodeVarintQot_SetPriceReminder(dAtA, i, uint64(m.Freq))
	i--
	dAtA[i] = 0x38
	i -= len(m.Note)
	copy(dAtA[i:], m.Note)
	i = encodeVarintQot_SetPriceReminder(dAtA, i, uint64(len(m.Note)))
	i--
	dAtA[i] = 0x32
	i -= 8
	encoding_binary.LittleEndian.PutUint64(dAtA[i:], uint64(math.Float64bits(float64(m.Value))))
	i--
	dAtA[i] = 0x29
	i = encodeVarintQot_SetPriceReminder(dAtA, i, uint64(m.Type))
	i--
	dAtA[i] = 0x20
	i = encodeVarintQot_SetPriceReminder(dAtA, i, uint64(m.Key))
	i--
	dAtA[i] = 0x18
	i = encodeVarintQot_SetPriceReminder(dAtA, i, uint64(m.Op))
	i--
	dAtA[i] = 0x10
	if m.Security == nil {
		return 0, github_com_gogo_protobuf_proto.NewRequiredNotSetError("security")
	} else {
		{
			size, err := m.Security.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintQot_SetPriceReminder(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *S2C) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *S2C) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *S2C) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	i = encodeVarintQot_SetPriceReminder(dAtA, i, uint64(m.Key))
	i--
	dAtA[i] = 0x8
	return len(dAtA) - i, nil
}

func (m *Request) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Request) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Request) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.C2S == nil {
		return 0, github_com_gogo_protobuf_proto.NewRequiredNotSetError("c2s")
	} else {
		{
			size, err := m.C2S.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintQot_SetPriceReminder(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *Response) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Response) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Response) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.S2C != nil {
		{
			size, err := m.S2C.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintQot_SetPriceReminder(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x22
	}
	i = encodeVarintQot_SetPriceReminder(dAtA, i, uint64(m.ErrCode))
	i--
	dAtA[i] = 0x18
	i -= len(m.RetMsg)
	copy(dAtA[i:], m.RetMsg)
	i = encodeVarintQot_SetPriceReminder(dAtA, i, uint64(len(m.RetMsg)))
	i--
	dAtA[i] = 0x12
	if m.RetType == nil {
		return 0, github_com_gogo_protobuf_proto.NewRequiredNotSetError("retType")
	} else {
		i = encodeVarintQot_SetPriceReminder(dAtA, i, uint64(*m.RetType))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func encodeVarintQot_SetPriceReminder(dAtA []byte, offset int, v uint64) int {
	offset -= sovQot_SetPriceReminder(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *C2S) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Security != nil {
		l = m.Security.Size()
		n += 1 + l + sovQot_SetPriceReminder(uint64(l))
	}
	n += 1 + sovQot_SetPriceReminder(uint64(m.Op))
	n += 1 + sovQot_SetPriceReminder(uint64(m.Key))
	n += 1 + sovQot_SetPriceReminder(uint64(m.Type))
	n += 9
	l = len(m.Note)
	n += 1 + l + sovQot_SetPriceReminder(uint64(l))
	n += 1 + sovQot_SetPriceReminder(uint64(m.Freq))
	return n
}

func (m *S2C) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	n += 1 + sovQot_SetPriceReminder(uint64(m.Key))
	return n
}

func (m *Request) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.C2S != nil {
		l = m.C2S.Size()
		n += 1 + l + sovQot_SetPriceReminder(uint64(l))
	}
	return n
}

func (m *Response) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.RetType != nil {
		n += 1 + sovQot_SetPriceReminder(uint64(*m.RetType))
	}
	l = len(m.RetMsg)
	n += 1 + l + sovQot_SetPriceReminder(uint64(l))
	n += 1 + sovQot_SetPriceReminder(uint64(m.ErrCode))
	if m.S2C != nil {
		l = m.S2C.Size()
		n += 1 + l + sovQot_SetPriceReminder(uint64(l))
	}
	return n
}

func sovQot_SetPriceReminder(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozQot_SetPriceReminder(x uint64) (n int) {
	return sovQot_SetPriceReminder(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *C2S) Unmarshal(dAtA []byte) error {
	var hasFields [1]uint64
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQot_SetPriceReminder
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: C2S: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: C2S: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Security", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQot_SetPriceReminder
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQot_SetPriceReminder
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQot_SetPriceReminder
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Security == nil {
				m.Security = &qotcommon.Security{}
			}
			if err := m.Security.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
			hasFields[0] |= uint64(0x00000001)
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Op", wireType)
			}
			m.Op = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQot_SetPriceReminder
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Op |= int32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			hasFields[0] |= uint64(0x00000002)
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Key", wireType)
			}
			m.Key = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQot_SetPriceReminder
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Key |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Type", wireType)
			}
			m.Type = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQot_SetPriceReminder
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Type |= int32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 5:
			if wireType != 1 {
				return fmt.Errorf("proto: wrong wireType = %d for field Value", wireType)
			}
			var v uint64
			if (iNdEx + 8) > l {
				return io.ErrUnexpectedEOF
			}
			v = uint64(encoding_binary.LittleEndian.Uint64(dAtA[iNdEx:]))
			iNdEx += 8
			m.Value = float64(math.Float64frombits(v))
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Note", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQot_SetPriceReminder
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQot_SetPriceReminder
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQot_SetPriceReminder
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Note = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 7:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Freq", wireType)
			}
			m.Freq = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQot_SetPriceReminder
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Freq |= int32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipQot_SetPriceReminder(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthQot_SetPriceReminder
			}
			if (iNdEx + skippy) < 0 {
				return ErrInvalidLengthQot_SetPriceReminder
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}
	if hasFields[0]&uint64(0x00000001) == 0 {
		return github_com_gogo_protobuf_proto.NewRequiredNotSetError("security")
	}
	if hasFields[0]&uint64(0x00000002) == 0 {
		return github_com_gogo_protobuf_proto.NewRequiredNotSetError("op")
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *S2C) Unmarshal(dAtA []byte) error {
	var hasFields [1]uint64
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQot_SetPriceReminder
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: S2C: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: S2C: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Key", wireType)
			}
			m.Key = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQot_SetPriceReminder
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Key |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			hasFields[0] |= uint64(0x00000001)
		default:
			iNdEx = preIndex
			skippy, err := skipQot_SetPriceReminder(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthQot_SetPriceReminder
			}
			if (iNdEx + skippy) < 0 {
				return ErrInvalidLengthQot_SetPriceReminder
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}
	if hasFields[0]&uint64(0x00000001) == 0 {
		return github_com_gogo_protobuf_proto.NewRequiredNotSetError("key")
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *Request) Unmarshal(dAtA []byte) error {
	var hasFields [1]uint64
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQot_SetPriceReminder
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Request: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Request: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field C2S", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQot_SetPriceReminder
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQot_SetPriceReminder
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQot_SetPriceReminder
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.C2S == nil {
				m.C2S = &C2S{}
			}
			if err := m.C2S.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
			hasFields[0] |= uint64(0x00000001)
		default:
			iNdEx = preIndex
			skippy, err := skipQot_SetPriceReminder(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthQot_SetPriceReminder
			}
			if (iNdEx + skippy) < 0 {
				return ErrInvalidLengthQot_SetPriceReminder
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}
	if hasFields[0]&uint64(0x00000001) == 0 {
		return github_com_gogo_protobuf_proto.NewRequiredNotSetError("c2s")
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *Response) Unmarshal(dAtA []byte) error {
	var hasFields [1]uint64
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQot_SetPriceReminder
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Response: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Response: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field RetType", wireType)
			}
			var v int32
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQot_SetPriceReminder
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.RetType = &v
			hasFields[0] |= uint64(0x00000001)
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field RetMsg", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQot_SetPriceReminder
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQot_SetPriceReminder
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQot_SetPriceReminder
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.RetMsg = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field ErrCode", wireType)
			}
			m.ErrCode = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQot_SetPriceReminder
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.ErrCode |= int32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field S2C", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQot_SetPriceReminder
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQot_SetPriceReminder
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQot_SetPriceReminder
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.S2C == nil {
				m.S2C = &S2C{}
			}
			if err := m.S2C.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQot_SetPriceReminder(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthQot_SetPriceReminder
			}
			if (iNdEx + skippy) < 0 {
				return ErrInvalidLengthQot_SetPriceReminder
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}
	if hasFields[0]&uint64(0x00000001) == 0 {
		return github_com_gogo_protobuf_proto.NewRequiredNotSetError("retType")
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipQot_SetPriceReminder(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowQot_SetPriceReminder
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowQot_SetPriceReminder
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
			return iNdEx, nil
		case 1:
			iNdEx += 8
			return iNdEx, nil
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowQot_SetPriceReminder
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthQot_SetPriceReminder
			}
			iNdEx += length
			if iNdEx < 0 {
				return 0, ErrInvalidLengthQot_SetPriceReminder
			}
			return iNdEx, nil
		case 3:
			for {
				var innerWire uint64
				var start int = iNdEx
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return 0, ErrIntOverflowQot_SetPriceReminder
					}
					if iNdEx >= l {
						return 0, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					innerWire |= (uint64(b) & 0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				innerWireType := int(innerWire & 0x7)
				if innerWireType == 4 {
					break
				}
				next, err := skipQot_SetPriceReminder(dAtA[start:])
				if err != nil {
					return 0, err
				}
				iNdEx = start + next
				if iNdEx < 0 {
					return 0, ErrInvalidLengthQot_SetPriceReminder
				}
			}
			return iNdEx, nil
		case 4:
			return iNdEx, nil
		case 5:
			iNdEx += 4
			return iNdEx, nil
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
	}
	panic("unreachable")
}

var (
	ErrInvalidLengthQot_SetPriceReminder = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowQot_SetPriceReminder   = fmt.Errorf("proto: integer overflow")
)
